### ISSUE TITLE
Problem with out.sam: No header 

### ISSUE THREAD

**Issue by sari-khaleel** [jstjohn/SimSeq#1]
Hello, I installed and ran SimSeq according to the README file and then I tried to view the created out.sam using samtools:

[khaleel@alanine examples]$ samtools view out.sam 
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[main_samview] fail to read the header from "out.sam".

I get the same error from /SimSeq/jstjohn-SimSeq-72ce499/examples/out.sam 

Here are the first 5 lines from my out.sam and /SimSeq/jstjohn-SimSeq-72ce499/examples/out.sam :

[khaleel@alanine examples]$ head -5 out.sam
SimSeq_1    67  AlligatorMito   12685   255 100M    =   13087   502 GTCGTGCCATGAATTTGAGGCGGCCCCTCTGTTGACAACGCAACACTTACACGCTTCACTGCCCTACACTTCCTCCTTCCATTCGCCCTATTGGCTTCAC    BBGGDGFGGGFGC>@AGG=FFE>FFEGEAED5>5GDBDDFGEF5GGEF6?#F@FACDGEGEG?EEDC@==E#?F>EF=FD7##GEFGCF<#-6EDB##BG    YC:Z:100M
SimSeq_1    131 AlligatorMito   13087   255 100M    =   12685   -502    ATATTCTCATCCATTTTAGTCCTATTCCTAATACCCGCCCTACACACAGCAAAACAACAACCAATATCAATACGCCCTATATCTCAGCTTCTATTTTGAG    G=?FDEGFA3GDFGGGG?G?G?FAG+F=EECAAFDF;:DGGGEABGD<G.#F6EGG=AF#G7A6GEGE-==BDE=@#?EAA.#D;C5AE;A#DFAEC<<#    YC:Z:100M
SimSeq_2    67  AlligatorMito   5157    255 100M    =   9605    -4448   CCTCAGACGTTCAAGAAGTAGAAGTAATCTGAACCGTCCTACCAGCCATTGTCCTTATCTCAATTGCCCTACCATCACTACGCACCCGATACCTCATCGA    FFDG.CG=FFEFG5DFGEBEGDECECE>F==EBEFFE:=AGCGGEB@D?GFBFAF9%EFG@+BB?<CFEF9ED>:EDBG?E==6B#D#<?ACEDE>F##E    YC:Z:100M
SimSeq_2    131 AlligatorMito   9605    255 89M11S  =   5157    4448    ACTGCTAATTCCTAGCCCCCAGGACTAACAGCCTGGCCCTCTCGTCGTGGGCTCGGTAAGTATAGTTTAAACAAAACATTAGAATGTGACACTACCACCA    ECGFGFDBDA:CF?-EEC#DEFDGDF+>=F@FGCE;A?E=EDG:E:CG9CDEED?=EAEE=#?GDGE=B??EG?DE_##AF#;A###@F##+?B?66CFB    YC:Z:89M-4801N11M
SimSeq_3    67  AlligatorMito   2637    255 100M    =   6962    -4325   TTATACCAAAATGATTAACAATCAACCAACTCCTCGCAGAAAAAGCAATTTGAATTGCACAATTAATACTAATTACATCCCTTCTAAGTCTATTCTTCTA    BEF=6=F=GGC6DGFCGFFAEFF:GEGDCG.EGGG>GDE-A4?G:DGFGB(D;FDD=FEF_?E#BEC???4B=CGD#F21?E7E::B5:A:A=?D8E5#:    YC:Z:100M

**Comment by jstjohn** [comment]
Hello, thanks for your interest in SeqPrep. This is a pretty easy fix in samtools. You need to provide samtools view the -T and -t arguments and then samtools will make the appropriate header for you given a sam file without a head.

The -t option requires a file with `seqid[TAB]length` on each line for each fasta sequence in your reference. You can simply run `samtools faidx reference.fa` which outputs a file `reference.fa.fai`. The .fai file can be used for the -t argument.

The -T option is simply the path to the reference fasta file.

Hope this helps!

**Comment by sari-khaleel** [comment]
Thank you for the prompt response ! I'll try it and get back to you.

Sari
