### ISSUE TITLE
Null pointer on SamToFastq

### ISSUE THREAD

**Issue by gramarga** [jstjohn/SimSeq#3]
Hello, I understand SamToFastq.jar is part of Picard, but I just tried running the example exactly as you suggest and got the following error:

[Wed Feb 15 11:09:17 PST 2012] net.sf.picard.sam.SamToFastq INPUT=out.sorted.bam FASTQ=library.1.fastq SECOND_END_FASTQ=library.2.fastq INCLUDE_NON_PF_READS=true VALIDATION_STRINGENCY=SILENT    OUTPUT_PER_RG=false RE_REVERSE=true READ1_TRIM=0 READ2_TRIM=0 INCLUDE_NON_PRIMARY_ALIGNMENTS=false VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Wed Feb 15 11:09:17 PST 2012] OpenJDK 64-Bit Server VM 1.6.0_20-b20; Picard version: 1.62(1113)
[Wed Feb 15 11:09:18 PST 2012] net.sf.picard.sam.SamToFastq done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=506331136
Exception in thread "main" java.lang.NullPointerException
        at net.sf.picard.sam.SamToFastq.doWork(SamToFastq.java:158)
        at net.sf.picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:177)
        at net.sf.picard.sam.SamToFastq.main(SamToFastq.java:121)

Is this a known issue or something that might have changed within Picard?
Thank you!

**Comment by jstjohn** [comment]
Huh... is there anything else to the error message? How exactly did you
call SamToFastq? I'll check into running it again later myself with the
latest picard, I don't know why it would stop working for this.

On Wed, Feb 15, 2012 at 1:07 PM, gramarga <
reply@reply.github.com

**Comment by gramarga** [comment]
I just ran exactly as suggested in the README (just adding a missing 'm' to the maximum heap size):

java -jar -Xmx2048m $HOME/jars/SamToFastq.jar INPUT=out.sorted.bam FASTQ=library.1.fastq SECOND_END_FASTQ=library.2.fastq INCLUDE_NON_PF_READS=true VALIDATION_STRINGENCY=SILENT

Nothing else to the error message... SimSeq apparently worked fine and I managed to see the alignments after running all the samtools commands.

**Comment by jstjohn** [comment]
Yep, I get the same error as you do. If you want to take the time I would notify Picard about this bug. I have been using a recent version of Picard, 1.60, that does work (just double checked). You can get that version here:
http://sourceforge.net/projects/picard/files/picard-tools/1.60/

Not sure if 1.61 works or not, but 1.62 does appear to have the issue you stated.

**Comment by gramarga** [comment]
Same thing here: 1.60 did the trick! It seemed to be a Picard issue, but always good to check with the dev :)
Thanks for the very fast reply and help.
All the best,
Gabriel
